### PR TITLE
Fix compile error for Mbed TF-M V8M target (2)

### PR DESCRIPTION
**Pull request by ccli8**
[x] I confirm this contribution is my own and I agree to license it with Apache 2.0.
[x] I confirm the moderators may change the PR before merging it in.
[x] I understand the release model prohibits detailed Git history and my contribution will be recorded to the list at the bottom of [CONTRIBUTING.md](CONTRIBUTING.md).

### Summary of changes 

Continuing #88, this PR tries to fix more compile error for Mbed TF-M V8M target, usually without `FLASHIAP`. In `arm_uc_config.h`:
1. Use `DEVICE_FLASH` as prerequisite to enable `ARM_UC_FEATURE_PAL_FLASHIAP`
1. Use `ARM_UC_FEATURE_PAL_FLASHIAP` as prerequisite to enable `ARM_UC_FEATURE_PAL_FILESYSTEM`

@marcuschangarm

### CODE REVIEW

**Comment by marcuschangarm** [comment]
@ccli8 Thank you! I'll take a look!

**Comment by marcuschangarm** [comment]
@ccli8 I think it would be better to add a new section for PSA, once it is ready, so that is looks like the other configurations. For example:

```
#elif defined(UPDATE_CLIENT_STORAGE_PSA)
#define ARM_UC_FEATURE_PAL_FLASHIAP 0
#define ARM_UC_FEATURE_PAL_FLASHIAP_MCUBOOT 0
#define ARM_UC_FEATURE_PAL_BLOCKDEVICE 0
#define ARM_UC_FEATURE_PAL_FILESYSTEM 0
#define ARM_UC_FEATURE_PAL_LINUX 0
#define ARM_UC_FEATURE_PAL_RTL8195AM 0
#define ARM_UC_FEATURE_PAL_PSA 1
```

You could then name your implementation `UPDATE_CLIENT_STORAGE_PSA` and hide the code behind the define `ARM_UC_FEATURE_PAL_PSA `.

**Comment by ccli8** [comment]
With above modification, this PR is replaced with #92.

**Comment by marcuschangarm** [comment]
@ccli8 sounds good, lets close this PR and continue the conversation in the other one.

**Comment by ccli8** [comment]
Close because #92 will cover this one

**Pull request closed without merging**
